baseURL = 'https://myrtenasty.github.io/relearn-doc.github.io/'
languageCode = 'en-us'
title = 'A Relearn Doc Site'
theme = "hugo-theme-relearn"

[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
  mathJaxInitialize = "{ \"chtml\": { \"displayAlign\": \"left\" } }"